# Generated by Django 4.2.14 on 2024-07-17 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0005_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='/Desktop/programming/project/radman_site/Radman-site/radman-site/static/img/portfolio/p2.jpg', upload_to='WEBLOG/'),
        ),
    ]
