# Generated by Django 4.2.14 on 2024-07-17 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0007_alter_post_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='weblog/image_file/p2.jpg', upload_to='weblog/'),
        ),
    ]
