# Generated by Django 4.2.14 on 2024-07-18 15:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0009_catgory_post_category'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catgory',
            new_name='Category',
        ),
    ]
