# Generated by Django 4.2.14 on 2024-07-18 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0010_rename_catgory_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image_single_blog',
            field=models.ImageField(default='weblog/image_file/p2.jpg', upload_to='weblog/'),
        ),
    ]
