# Generated by Django 4.2.14 on 2024-07-19 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0011_post_image_single_blog'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='writer_image',
            field=models.ImageField(default='weblog/image_file/p2.jpg', upload_to='weblog/'),
        ),
        migrations.AddField(
            model_name='post',
            name='writer_linkedin_account',
            field=models.URLField(default='https://www.linkedin.com/in/kian-almasi-0a4016256/'),
        ),
        migrations.AddField(
            model_name='post',
            name='writer_summary',
            field=models.CharField(default='No summary available', max_length=255),
        ),
    ]
