# Generated by Django 4.2.14 on 2024-07-19 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0012_post_writer_image_post_writer_linkedin_account_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='writer_summary',
            field=models.TextField(),
        ),
    ]
