# Generated by Django 4.2.14 on 2024-07-27 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0013_alter_post_writer_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(null=True),
        ),
    ]
