# Generated by Django 4.2.14 on 2024-07-31 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0018_comments_post'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comments',
            old_name='approach',
            new_name='approved',
        ),
    ]
