# Generated by Django 4.2.14 on 2024-07-31 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weblog', '0019_rename_approach_comments_approved'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-created_date']},
        ),
    ]
