# Generated by Django 4.2.14 on 2024-08-09 14:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('weblog', '0020_alter_comments_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'دسته بندی ', 'verbose_name_plural': 'دسته بندی ها'},
        ),
        migrations.AlterModelOptions(
            name='comments',
            options={'ordering': ['-created_date'], 'verbose_name': 'نظر مورد', 'verbose_name_plural': 'نظر ها'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-created_date', 'updated_date'], 'verbose_name': 'پست مورد', 'verbose_name_plural': 'پست ها'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=255, verbose_name='اسم دسته بندی :'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='approved',
            field=models.BooleanField(default=False, verbose_name='تایید شده است:'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت:'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='ایمیل:'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='message',
            field=models.TextField(verbose_name='پیام:'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='name',
            field=models.CharField(max_length=255, verbose_name='اسم:'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weblog.post', verbose_name='اسم پست:'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='subject',
            field=models.CharField(max_length=255, verbose_name='موضوع:'),
        ),
        migrations.AlterField(
            model_name='comments',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی:'),
        ),
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده:'),
        ),
        migrations.AlterField(
            model_name='post',
            name='category',
            field=models.ManyToManyField(to='weblog.category', verbose_name='دسته بندی:'),
        ),
        migrations.AlterField(
            model_name='post',
            name='content',
            field=models.TextField(verbose_name='متن:'),
        ),
        migrations.AlterField(
            model_name='post',
            name='counted_view',
            field=models.IntegerField(default=0, verbose_name='تعداد بازدید ها:'),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت پست:'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='weblog/image_file/p2.jpg', upload_to='weblog/', verbose_name='تصویر بالای متن:'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image_single_blog',
            field=models.ImageField(default='weblog/image_file/p2.jpg', upload_to='weblog/', verbose_name='تصویر پایین متن:'),
        ),
        migrations.AlterField(
            model_name='post',
            name='published_date',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ نشر پست:'),
        ),
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.BooleanField(default=False, verbose_name='وضعیت پست'),
        ),
        migrations.AlterField(
            model_name='post',
            name='tag',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='برچسب زدن:'),
        ),
        migrations.AlterField(
            model_name='post',
            name='title',
            field=models.CharField(max_length=255, verbose_name='عنوان پست:'),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی پست:'),
        ),
        migrations.AlterField(
            model_name='post',
            name='writer_image',
            field=models.ImageField(default='weblog/image_file/p2.jpg', upload_to='weblog/', verbose_name='عکس نویسنده:'),
        ),
        migrations.AlterField(
            model_name='post',
            name='writer_linkedin_account',
            field=models.URLField(default='https://www.linkedin.com/in/kian-almasi-0a4016256/', verbose_name='آدرس حساب کاربری لینکدین نویسنده:'),
        ),
        migrations.AlterField(
            model_name='post',
            name='writer_summary',
            field=models.TextField(verbose_name='درباره نویسنده:'),
        ),
    ]
