# Generated by Django 4.2.14 on 2024-07-12 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_contact'),
    ]

    operations = [
        migrations.DeleteModel(
            name='post',
        ),
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-created_date', 'updated_date']},
        ),
    ]
