# Generated by Django 4.2.14 on 2024-08-09 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_newsletter'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['-created_date', 'updated_date'], 'verbose_name': 'درخواست مورد نظر', 'verbose_name_plural': 'پیام های ارتباط با ما'},
        ),
        migrations.AlterModelOptions(
            name='newsletter',
            options={'verbose_name': 'ایمیل مورد نظر', 'verbose_name_plural': 'ایمیل های اخرین اخبارها'},
        ),
    ]
