# Generated by Django 4.2.14 on 2024-08-14 23:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('taggit', '0006_rename_taggeditem_content_type_object_id_taggit_tagg_content_8fc721_idx'),
        ('blog', '0006_alter_contact_options_alter_newsletter_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(default='blog/image_file/new1.jpg', upload_to='blog/', verbose_name='تصویر:')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان:')),
                ('content', models.TextField(verbose_name='متن:')),
                ('status', models.BooleanField(default=False, verbose_name='وضعیت پست')),
                ('counted_view', models.IntegerField(default=0, verbose_name='تعداد بازدید ها:')),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ نشر:')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ساخت:')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ بروزرسانی:')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='نویسنده:')),
                ('tag', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='taggit.TaggedItem', to='taggit.Tag', verbose_name='برچسب زدن:')),
            ],
            options={
                'verbose_name': 'پروژه مورد',
                'verbose_name_plural': 'پروژه ها',
                'ordering': ['-created_date', 'updated_date'],
            },
        ),
    ]
