# Generated by Django 4.2.14 on 2024-08-16 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_project'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='image',
            new_name='image1',
        ),
        migrations.AddField(
            model_name='project',
            name='image2',
            field=models.ImageField(default='blog/image_file/new1.jpg', upload_to='blog/', verbose_name='تصویر:'),
        ),
        migrations.AddField(
            model_name='project',
            name='image3',
            field=models.ImageField(default='blog/image_file/new1.jpg', upload_to='blog/', verbose_name='تصویر:'),
        ),
    ]
