# Generated by Django 4.2.14 on 2024-08-17 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_rename_image_project_image1_project_image2_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.CharField(max_length=255, verbose_name='اسم مشتری:', null=True, blank=True, default=''),
            preserve_default=False,
        ),
    ]

