# Generated by Django 4.2.14 on 2024-08-17 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_project_client'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='client',
            field=models.CharField(default=False, max_length=255, verbose_name='اسم مشتری:'),
        ),
    ]
