# Generated by Django 4.2.14 on 2024-08-17 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_remove_project_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.CharField(default='default_client', max_length=255, verbose_name='اسم مشتری:'),
        ),
    ]
