# Generated by Django 4.2.14 on 2024-08-17 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_remove_project_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='client',
            field=models.CharField(blank=True, default='', max_length=255, null=True, verbose_name='اسم مشتری:'),
        ),
    ]
